[package]
name = "idyllic-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
insta = "1.44.3"
lasso = { version = "0.7.3", features = ["multi-threaded"] }
log = "0.4.29"
once_cell = "1.21.3"
