[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
codac = { path = "../compiler" }
clap = "4.5.53"
env_logger = "0.11.8"
insta = "1.44.3"
log = "0.4.29"
rustyline = { version = "17.0.2", features = ["with-file-history", "derive"] }
